### ISSUE TITLE
don't do async response for ephemeral messages

### ISSUE THREAD

**Issue by lexelby** [heroku/retrodot#174]
If the response to a /-command is an ephemeral message, we should just send it right away rather than doing the async HTTP POST.  With async, we get this:

![async_fail](https://cloud.githubusercontent.com/assets/4446653/21695427/c79248f4-d357-11e6-88f0-b689fdd58fa5.png)

**Comment by jmervine** [comment]
@lexelby is this a fix for #173 or was it caused by it?

**Comment by lexelby** [comment]
#173 caused this.  I didn't manage to catch it during testing.

**Comment by jmervine** [comment]
Okay cool. I can take a look Monday.

**Comment by joshuatobin** [comment]
Fixed in https://github.com/heroku/retrodot/pull/193
