### ISSUE TITLE
link to incident in staging is not relative (it links to production)

### ISSUE THREAD

**Issue by CobyR** [heroku/retrodot#175]

**Comment by jmervine** [comment]
I'm guessing this is due to ...

```
jmervine@laptop:~/Development/retrodot$ heroku config:get STATUS_SITE_URL -s -a retrodot-staging
STATUS_SITE_URL='https://status.heroku.com/incidents'
```

@lexelby @joshuatobin do you see any issue with updating this to point to staging status in retrodot-staging?

**Comment by joshuatobin** [comment]
@jmervine yeah should be fine.

**Comment by jmervine** [comment]
@joshuatobin I made this change, but now we need to resync staging against status-staging incidents, as the links don't work =P

**Comment by jmervine** [comment]
Looks like, that's from ...

```
👉  🐧  ~/Development/retrodot 👉  h config:get SOURCE_URL -s -a retrodot-staging
SOURCE_URL='https://status.heroku.com/api/v4/incidents'
```

Perhaps we should consider just setting `STATUS_DOMAIN=status-staging.heroku.com` and using that to generate both the links and the source?

cc @lexelby

**Comment by lexelby** [comment]
Yeah, the open source thing makes it tricky.  Ultimately all of this should probably be abstracted out better.

**Comment by joshuatobin** [comment]
This should be all set. I've updated `SOURCE_URL` as it was breaking other things as well.
