### ISSUE TITLE
Feature Request: Timeline reaction should add to last incident if no incident is currently running

### ISSUE THREAD

**Issue by peculiaire** [heroku/retrodot#176]
I would like to be able to add stuff to the timeline of a previous incident via reaction. 

User story:

Owen comes into P-I and notifies us that we had a build outage. It's since been resolved. IC/Comms post a retroactive incident. IC adds timeline reaction to chat to build a timeline for the retroactive incident.

**Comment by lexelby** [comment]
I wondered if there might be a use case for that.  Thanks for the detailed description!  Should be low-effort.

**Comment by joshuatobin** [comment]
@lexelby @jmervine Should just be a tweak to https://github.com/heroku/retrodot/blob/master/app/controllers/api/v1/chat_ops_controller.rb#L55

Thoughts on ill effects?

**Comment by lexelby** [comment]
At worst (and unlikely) this attaches a timeline entry to the wrong incident.  People can edit timelines in their google docs, so I feel like it's low-impact.

**Comment by jmervine** [comment]
I think there's a trello card for this. I know I called it out in user-testing. Not just adding to timeline, but for the following commands as well...

```
/i who
/i timeline
/i add <person>
/i rm <person>
```

**Comment by jmervine** [comment]
We should also update the admin interface as part of this to allow for editing responders and timelines.

**Comment by joshuatobin** [comment]
Closing as this has been merged
