### ISSUE TITLE
Retroactive incident did not start automatically timeline

### ISSUE THREAD

**Issue by reidmix** [heroku/retrodot#177]
When creating a retroactive incident, I expected a timeline would have been created via webhook.

**Comment by jmervine** [comment]
In retrodot, we're only explicitly omitting `scheduled` and `maintenance` ([referenced here](https://github.com/heroku/retrodot/blob/master/app/controllers/api/v1/webhooks_controller.rb#L28)).

In status, we're only explicitly omitting update types with the `silent` implementation ([here](https://github.com/heroku/status/blob/master/app/models/update_type.rb)), in which, "retroactive" is not omitted.

Thus, this is a bug. We're going to need to dig deeper.

**Comment by joshuatobin** [comment]
This should be all set. The webhooks were not setup properly.
