### ISSUE TITLE
Feature Request: autocomplete email addresses when sending retro email

### ISSUE THREAD

**Issue by reidmix** [heroku/retrodot#179]
Until we know the team manager & teams automatically, it'd be nice to have an auto-complete of email addresses when I'm sending the retro email similar to how mail does it.

**Comment by lexelby** [comment]
+1

**Comment by lexelby** [comment]
Oops.  Wrong button.

**Comment by lexelby** [comment]
Doesn't look like there's anything close to an API for gathering this information or auto-completing email addresses.  Our best bet may be to open a gmail composition window, which handily solves the problem I had too, which is that sometimes I want to edit the message.  Check this out: http://stackoverflow.com/a/8852679/4249120

**Comment by joshuatobin** [comment]
Maybe a long shot but we probably could have retrodot accept CC/BCC messages and save them to the db so we have a record of the thread?

**Comment by lexelby** [comment]
I think that might be doable!  That'd be neat.  Probably should be a separate ticket though.

**Comment by lexelby** [comment]
Ah, I see the problem: without having retrodot receive a CC/BCC, it won't know for sure that the retro email has been sent.

Another problem is that the URL technique described above for pre-filling a gmail compose window doesn't allow HTML.  That means we can't do things like the bold/red "This incident will need a public postmortem" message.  We could sort of do bold with unicode math bold characters like this:

𝗧𝗵𝗶𝘀 𝗶𝗻𝗰𝗶𝗱𝗲𝗻𝘁 𝘄𝗶𝗹𝗹 𝗻𝗲𝗲𝗱 𝗮 𝗽𝘂𝗯𝗹𝗶𝗰 𝗽𝗼𝘀𝘁𝗺𝗼𝗿𝘁𝗲𝗺 𝗯𝘆 𝟮𝟬𝟭𝟳-𝟬𝟭-𝟬𝟯.

That was generated using this tool: http://qaz.wtf/u/convert.cgi?text=This+incident+will+need+a+public+postmortem+by+2017-01-03.

Kind of hacky and I can't find a gem to do that kind of translation, so we'd have to write one ourselves or something.  Thoughts?

**Comment by lexelby** [comment]
Fixed by #201
