### ISSUE TITLE
Past Incidents: Days Since Last Incident - Formula Parse Errors

### ISSUE THREAD

**Issue by reidmix** [heroku/retrodot#182]
In the Past Incidents spreadsheet & tab, the column "Days Since Last Incident" (Q) has Formula Parse Errors.

Looks like the formula `=J9 - J10` for the new rows is set on the wrong column, (Should be K instead of J).  

I've manually updated the problematic columns in the spreadsheet.  But I'm not sure if that something that gets exported from Retrodot or not.

**Comment by lexelby** [comment]
Nope, that's generated in the script attached to the spreadsheet.  I'll have to go in and fix it when I get a chance.

**Comment by lexelby** [comment]
Fixed.
