### ISSUE TITLE
Primary Team does not get set when updating an Incident

### ISSUE THREAD

**Issue by reidmix** [heroku/retrodot#183]
I'm trying to set the primary team in retrodot when editing an incident.  I'm setting the team to Dogwood on incident 995.

Step:
1. Click Edit on the incident
2. Set the Primary team from the drop down
3. Click Update Incident
4. Notice that "Primary Team" is "EMPTY"

**Comment by reidmix** [comment]
This is also happening on "Retro at".
When I set the "Category" or "Retro Email Sent", those do get saved.

**Comment by joshuatobin** [comment]
I believe this has to do with how ActiveAdmins forms are configured. The docs for this aren't great. I've tried using `permit_params` without much luck. http://activeadmin.info/docs/5-forms.html
