### ISSUE TITLE
New Retro trello cards should go into "Needs Retro"

### ISSUE THREAD

**Issue by reidmix** [heroku/retrodot#184]
The trello cards for a retro on the Production Incidents trello board used to go into "Needs Retro" and I think still should.  Right now they are going into the "Start Here" which has instructions and templates.

**Comment by joshuatobin** [comment]
@reidmix Not sure if the LOE here is gonna be worth it or not. AFAICT there isn't an easy way to get the `ListID` for a board using a string. Could be I'm misunderstanding the documentation but I can't seem to get it working. http://www.rubydoc.info/gems/ruby-trello

**Comment by lexelby** [comment]
I think you can go from the template card to the list it's in, from there to the board, and then get a list of lists in the board and find the one you want.  I think I did something like that in the old google script.  It is kind of a pain though, and yeah, probably not worth the LOE if we're going to get rid of trello.

**Comment by reidmix** [comment]
@lexelby you are going to laugh -- we figured out you can add `.json` to the url for any board and get the list ids from there (amongst everything else)

**Comment by lexelby** [comment]
Wow, easy!

**Comment by joshuatobin** [comment]
Fixed in https://github.com/heroku/retrodot/pull/194
