### ISSUE TITLE
35 Incident cards for 1009

### ISSUE THREAD

**Issue by reidmix** [heroku/retrodot#185]
Not sure what happened to incident 1009 but about +/- 40 cards got created in trello for it.  Thankfully only one gdoc got created for all of them.   I'm putting them into a "Triage" column for investigations.

**Comment by joshuatobin** [comment]
🙀

**Comment by lexelby** [comment]
Maybe my fault?  Not sure?  I thought I did my testing in staging but perhaps I did some in production.

**Comment by joshuatobin** [comment]
Going to label this as wont fix. Looks like testing was done in the wrong env.

**Comment by lexelby** [comment]
Turns out it was due to a redirect loop: #214
