### ISSUE TITLE
Category and Primary Team don't get updated in Past Incidents

### ISSUE THREAD

**Issue by reidmix** [heroku/retrodot#190]
Category and Team usually get added later than when the incident is created.  It'd be nice for when they are not set in the Past Incidents spreadsheet for them to get updated if there's a value in Retrodot.

**Comment by lexelby** [comment]
This is a bug.  They should get updated, so something went wrong with the javascript.

**Comment by lexelby** [comment]
Fixed.  Retrodot is the source of truth now, and all fields are properly copied into Past Incidents, including category, primary team, trello / gdoc URLs, etc.  Don't make any more changes in Past Incidents, since they'll be overwritten next time the script runs.

cc @cme
