### ISSUE TITLE
redirect loop in "prepare retro"

### ISSUE THREAD

**Issue by lexelby** [heroku/retrodot#214]
Any error in the creation of the trello card or google doc is treated as an authentication error, and the user is redirected through the OAuth flow.  If the problem is not actually authentication-based (e.g. if it's a matter of permissions/authorization), then this results in a redirect loop.

Similarly, if a user's Google login session has expired, in some cases, Google OAuth will silently return failure to our oauth callback.  This also results in a redirect loop.

**Comment by lexelby** [comment]
Another effect of this is that the trello card is created over and over again if the google doc creation fails.

**Comment by reidmix** [comment]
There used to be a card for that 😄 https://github.com/heroku/retrodot/issues/185
