### ISSUE TITLE
edit some fields in table view

### ISSUE THREAD

**Issue by lexelby** [heroku/retrodot#224]
Retrodot is currently a step back from our old spreadsheet, efficiency-wise.  To edit the "retro at" date for an incident requires several page-loads, where previously we could just edit the value right in the cell in the spreadsheet.

We can use a technique like this to allow editing these fields directly in the incident list view:

https://amolnpujari.wordpress.com/2013/10/23/activeadmin-cool-tweaks/

cc @cmeckhardt

**Comment by lexelby** [comment]
use jqueryui's `.datepicker()` http://jqueryui.com/datepicker/

**Comment by cmeckhardt** [comment]
<# <# <#

Thanks @lexelby for creating this on my behalf, and for doing the research.

**Comment by lexelby** [comment]
done: #231
