### ISSUE TITLE
Manually updating the "retro email sent" check box doesn't work

### ISSUE THREAD

**Issue by cmeckhardt** [heroku/retrodot#228]
Incident 1046 and 1047 have the same root cause, so I used incident 1047 to send one email and modified it to include the information about incident 1046.  I tried to update incident 1046 to reflect that an email has been sent for this, and even though I get the `Incident was successfully updated.` message, it doesn't work- this incident still shows that no email has been sent.

**Comment by lexelby** [comment]
Awesome use case, thanks!  This should be a quick fix.

**Comment by lexelby** [comment]
fixed by #231
