### ISSUE TITLE
"did you really mean incident X" thing is annoying

### ISSUE THREAD

**Issue by lexelby** [heroku/retrodot#236]
The "It loos like you may have forgotten to run `start` for this incident." message is actually pretty annoying.  Almost always, I mean to be acting on the most recent incident.  I end up having to copy and paste my command in.  Retrodot could perhaps handle this better, by returning an error to slack, whcih causes one's client to keep the command in the edit line.

**Comment by VxJasonxV** [comment]
Perhaps the chat event should remain open for 30 minutes to an hour after an event is resolved? Pick up the trailing discussion that inevitably occurs after an incident wraps? It should always be closed explicitly, the 30 minutes/1 hour timeline would serve as a safety fallback.
